package com.addressbook.pl;

import java.io.Serializable;

public class Address implements Serializable {
	private static final long serialVersionUID = 1L;
	private String street;
	private String city;
	private String country;
	private String postalCode;

	public Address(String street, String city, String country, String postalCode) {
		this.street = street;
		this.city = city;
		this.country = country;
		this.postalCode = postalCode;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return country;
	}

	public void setCounty(String county) {
		this.country = county;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Override
	public String toString() {
		return "[" + street + " " + city + " " + country + " " + postalCode + "]";
	}

	// GENERATED BY ECLIPSE
	@Override
	public int hashCode() {
		int result = 17;
		result = 31 * result + ((city == null) ? 0 : city.hashCode());
		result = 31 * result + ((country == null) ? 0 : country.hashCode());
		result = 31 * result + ((postalCode == null) ? 0 : postalCode.hashCode());
		result = 31 * result + ((street == null) ? 0 : street.hashCode());
		return result;
	}

	// GENERATED BY ECLIPSE TODO CHANGE
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Address other = (Address) obj;
		if (city == null) {
			if (other.city != null)
				return false;
		} else if (!city.equals(other.city))
			return false;
		if (country == null) {
			if (other.country != null)
				return false;
		} else if (!country.equals(other.country))
			return false;
		if (postalCode == null) {
			if (other.postalCode != null)
				return false;
		} else if (!postalCode.equals(other.postalCode))
			return false;
		if (street == null) {
			if (other.street != null)
				return false;
		} else if (!street.equals(other.street))
			return false;
		return true;
	}
}
